name: workflow-practica
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linter execution
        run: npm install --save-dev eslint && npx next lint

  Cypress_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        continue-on-error: true
      - name: Upload-Artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: artifact/result.txt

# npx next build
# npm start
# npm run cypress

  # test-execution:
  #   runs-on: ubuntu-latest
  #   # needs: linter-execution
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Run jest tests
  #       id: test
  #       run: npm install jest && npm test
  #       continue-on-error: true
  #     - name: Print error
  #       if: steps.test.outcome != 'success'
  #       run: echo "El test ha fallado"

  #     # - name: Send mail
  #     #   uses: dawidd6/action-send-mail@v3
  #     #   with:
  #     #     server_address: smtp.gmail.com
  #     #     username: ${{secrets.MAIL_USERNAME}}
  #     #     password: ${{secrets.MAIL_PASSWORD}}
  #     #     to: salroiba03@gmail.com
  #     #     from: Salva
  #     #     subject: Github Actions job result
  #     #     body: Mensaje enviado

  # environment_test_execution:
  #   runs-on: ubuntu-latest
  #   # needs: linter-execution
  #   steps:
  #     - name: Checkout code
  #       id: Hola
  #       uses: adeloyedeji/github-actions-hello@v1.0
  #       with:
  #         who-to-greet: "Pepe"
