name: workflow-practica
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linter execution
        run: npm install --save-dev eslint && npx next lint

  Cypress_job:
    runs-on: ubuntu-22.04
    needs: Linter_job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Server install
        run: npm install
      - name: Cypress run # Corregido un POST que ponía POST0
      - id: cypress_test
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        continue-on-error: true
      - name: Create file
        run: echo ${{ steps.cypress_test.outcome }}  > result.txt
      - name: Upload-Artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result.txt

  # Add_badge_job:
  #   runs-on: ubuntu-latest
  #   needs: Cypress_job
  #   if: ${{ always() }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Upload-Artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: result
  #     - name: Server install
  #       run: echo "::set-output name=cypress_outcome::$(cat result.txt)"

  #     - name: Custom action
  #       uses: ./.github/actions/badge
  #       env:
  #         res: ${{ needs.test-execution.result }}
  #     - name: Endbug
  #       uses: EndBug/add-and-commit@v9
  #       with:
  #         message: "Readme Updated succesfully"
  #         push: true

  # test-execution:
  #   runs-on: ubuntu-latest
  #   # needs: linter-execution
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Run jest tests
  #       id: test
  #       run: npm install jest && npm test
  #       continue-on-error: true
  #     - name: Print error
  #       if: steps.test.outcome != 'success'
  #       run: echo "El test ha fallado"

  #     # - name: Send mail
  #     #   uses: dawidd6/action-send-mail@v3
  #     #   with:
  #     #     server_address: smtp.gmail.com
  #     #     username: ${{secrets.MAIL_USERNAME}}
  #     #     password: ${{secrets.MAIL_PASSWORD}}
  #     #     to: salroiba03@gmail.com
  #     #     from: Salva
  #     #     subject: Github Actions job result
  #     #     body: Mensaje enviado

  # environment_test_execution:
  #   runs-on: ubuntu-latest
  #   # needs: linter-execution
  #   steps:
  #     - name: Checkout code
  #       id: Hola
  #       uses: adeloyedeji/github-actions-hello@v1.0
  #       with:
  #         who-to-greet: "Pepe"
