name: workflow-practica
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linter execution
        run: npm install --save-dev eslint && npx next lint

  Cypress_job:
    runs-on: ubuntu-22.04
    needs: Linter_job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Server install
        run: npm install
      - name: Cypress run # Corregido un POST que ponía POST0
        id: cypress_test
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        continue-on-error: true
      - name: Create file
        run: echo ${{ steps.cypress_test.outcome }}  > result.txt
      - name: Upload-Artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result.txt

  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    # if: ${{ always() }}
    steps:
      - name: Upload-Artifact
        uses: actions/download-artifact@v2
        with:
          name: result
      - name: Get file data
        id: data
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
      - name: Custom action
        uses: ./.github/actions/badge
        env:
          res: ${{ steps.data.outputs.cypress_outcome }}
      - name: Endbug
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Salva Roig"
          author_email: "salroiba03@gmail.com"
          message: "Readme Updated succesfully."
          push: true

  Deploy_job:
    needs: Cypress_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} #se optiene pulsando en el usuario y yendo a Settings > Tokens
          vercel-org-id: ${{ secrets.ORG_ID}} # En la cuenta, settings, general
          vercel-project-id: ${{ secrets.PROJECT_ID}} # En el dashboard del proyecto en settings
